Description: A template for creating EC2 instance

Parameters:
  EC2InstanceType:
    Description: EC2 instance type configuration
    Type: String
    Default: t2.micro
    AllowedValues:
        - t2.micro
        - t2.small
        - t2.medium
      

  EC2InstanceAmiId:
    Description: AMI identifier for the EC2 instance
    Type: String
    Default: ami-0747e613a2a1ff483

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2InstanceAmiId
      InstanceType: !Ref EC2InstanceType

Outputs:
  PublicIp:
    Description: EC2 Instance public IP
    Value: !GetAtt EC2Instance.PublicIp